### ISSUE TITLE
INFOGRAFIA

### ISSUE THREAD

**Issue by IMA-G** [SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-IMA-G#2]

**Comment by IMA-G** [comment]
[GESTION DE PROYECTOS DE SOFTWARE (1).pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-IMA-G/files/9433838/GESTION.DE.PROYECTOS.DE.SOFTWARE.1.pdf)

**Comment by josealfredo79** [comment]
Calificación 18
Bien hecho y revisado
